# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(712, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Bing.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 422, 244))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_reset = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 5, 1, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 5, 2, 1, 1)
        self.pushButton_OK = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_OK.setDefault(False)
        self.pushButton_OK.setFlat(False)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.gridLayout.addWidget(self.pushButton_OK, 5, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_1.setToolTipDuration(-1)
        self.checkBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 1, 0, 1, 2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 3, 0, 1, 2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 4, 0, 1, 2)
        self.spinBox_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_1.setWrapping(False)
        self.spinBox_1.setFrame(True)
        self.spinBox_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_1.setReadOnly(False)
        self.spinBox_1.setProperty("showGroupSeparator", False)
        self.spinBox_1.setMinimum(1)
        self.spinBox_1.setMaximum(31)
        self.spinBox_1.setProperty("value", 14)
        self.spinBox_1.setObjectName("spinBox_1")
        self.gridLayout.addWidget(self.spinBox_1, 1, 2, 1, 2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(60)
        self.spinBox_2.setProperty("value", 5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 2, 1, 2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(20)
        self.spinBox_3.setProperty("value", 3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 3, 2, 1, 2)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(60)
        self.spinBox_4.setSingleStep(1)
        self.spinBox_4.setProperty("value", 15)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 4, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.pushButton_exit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout.addWidget(self.pushButton_exit, 5, 3, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_OK.clicked.connect(Dialog.OK_buttonClick)
        self.pushButton_reset.clicked.connect(Dialog.Reset_buttonClick)
        self.pushButton_delete.clicked.connect(Dialog.Delete_buttonClick)
        self.pushButton_exit.clicked.connect(Dialog.Exit_buttonClick)
        self.checkBox_3.stateChanged['int'].connect(Dialog.Sync_Retry_3)
        self.checkBox_4.stateChanged['int'].connect(Dialog.Sync_Retry_4)
        self.spinBox_1.valueChanged['int'].connect(Dialog.Update_toolTip)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_OK, self.pushButton_reset)
        Dialog.setTabOrder(self.pushButton_reset, self.pushButton_delete)
        Dialog.setTabOrder(self.pushButton_delete, self.pushButton_exit)
        Dialog.setTabOrder(self.pushButton_exit, self.checkBox_1)
        Dialog.setTabOrder(self.checkBox_1, self.spinBox_1)
        Dialog.setTabOrder(self.spinBox_1, self.checkBox_2)
        Dialog.setTabOrder(self.checkBox_2, self.spinBox_2)
        Dialog.setTabOrder(self.spinBox_2, self.checkBox_3)
        Dialog.setTabOrder(self.checkBox_3, self.spinBox_3)
        Dialog.setTabOrder(self.spinBox_3, self.checkBox_4)
        Dialog.setTabOrder(self.checkBox_4, self.spinBox_4)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置器"))
        self.pushButton_reset.setToolTip(_translate("Dialog", "<html><head/><body><p>重置以上设定</p></body></html>"))
        self.pushButton_reset.setText(_translate("Dialog", "重设"))
        self.pushButton_delete.setToolTip(_translate("Dialog", "<html><head/><body><p>删除开机启动配置</p></body></html>"))
        self.pushButton_delete.setText(_translate("Dialog", "删除"))
        self.pushButton_OK.setToolTip(_translate("Dialog", "<html><head/><body><p>配置开机启动并立即执行</p></body></html>"))
        self.pushButton_OK.setText(_translate("Dialog", "确定"))
        self.checkBox_1.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">选中复选框并在右侧输入限制壁纸的数量</span></p><p>下载近<span style=\" font-weight:600;\">?n?</span>天缺失的必应每日一图，并存档不为近<span style=\" font-weight:600;\">?n?</span>天的图片。</p><p>最多可下载近15天图片。</p></body></html>"))
        self.checkBox_1.setText(_translate("Dialog", "限制壁纸数量"))
        self.checkBox_2.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">选中复选框并在右侧输入推送通知时长</span></p><p>不建议设置过小的数值。</p></body></html>"))
        self.checkBox_2.setText(_translate("Dialog", "推送通知时长"))
        self.checkBox_3.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">选中复选框并在右侧输入出错重试次数</span></p><p>建议设置此项以避免网络状况不良导致的程序失效。</p><p>不建议设置过大的数值。</p></body></html>"))
        self.checkBox_3.setText(_translate("Dialog", "出错重试次数"))
        self.checkBox_4.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">选中复选框并在右侧输入出错重试时间间隔</span></p><p>建议设置此项以避免网络状况不良导致的程序失效。</p><p>不建议设置过小或过大的数值。</p></body></html>"))
        self.checkBox_4.setText(_translate("Dialog", "出错重试间隔"))
        self.spinBox_2.setSuffix(_translate("Dialog", "    秒"))
        self.spinBox_4.setSuffix(_translate("Dialog", "    秒"))
        self.label.setText(_translate("Dialog", "必应每日一图"))
        self.pushButton_exit.setText(_translate("Dialog", "退出"))

